### ISSUE TITLE
Not showing button to POSSE on facebook

### ISSUE THREAD

**Issue by c-cesar** [idno/Facebook#13]
The facebook authentication seems to be working, but when creating a new post the button to enable Facebook share not appear. 
I can't find any logs, but I can delete the authorization on Facebook and reauthorize on my Known installation.

**Comment by cochise** [comment]
Today I tried Known again, bit with a different setup. 
Twitter callback and Facebook Posse seems to work. 
The main difference is my old setup was in a subdomain and the current inhalation is a main level. I used the Dreamhost panel to map the subdomain. 
In the end, I think the bug is not on the plugins, but in the core.

**Comment by benwerd** [comment]
Is this the latest code of both the plugins and core? And you're saying there's nothing in the error logs?

**Comment by cochise** [comment]
In the old installation I tried release and git. in the current only release and all is working.
If I can remember, the logs are empty in the old installation. The Twitter's callback returns a FOUND code on Apache logs and the Facebook links the account, but not enable the Facebook button when posting.

**Comment by mapkyca** [comment]
Going to close with a worksforme. Old ticket, so guessing this has been fixed loooong ago
